language: node_js

node_js:
  - node

install:
  - npm install -g codecov
  - npm install eslint --save-dev

script:
  - npm run test
  - npm run lint
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
