language: node_js

node_js:
  - node

install:
  - npm install -g codecov

script:
  - codecov
  - npm run lint
  - npm run build --if-present
  - npm test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
